### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by shaykeren** [digma-ai/digma-ui#1101]
posthog e6ecdb60ccdb6a1122abbd07b2bf6d1059f82bc1

Plugin:
2.0.384

IDE:
2024.1.1

Server:
DeploymentType:

App:
main

Level:
App react component

Frequency:
1

Severity:
high

Timestamp:
2024-09-12T19:31:37.280Z

Exception:
```
TypeError: Cannot read properties of undefined (reading 'filter')
   at t.ErrorDetailsCardContent (https://main/index.js:538:1167)
   at Ca (https://main/index.js:2:1296280)
   at xs (https://main/index.js:2:1307901)
   at Cl (https://main/index.js:2:1353979)
   at vc (https://main/index.js:2:1342264)
   at _c (https://main/index.js:2:1342192)
   at bc (https://main/index.js:2:1342055)
   at ac (https://main/index.js:2:1338862)
   at ic (https://main/index.js:2:1337417)
   at S (https://main/index.js:2:2730307)
   ```

**Comment by kshmidt-digma** [comment]
According to the stack trace the error occurs here:
https://github.com/digma-ai/digma-ui/blob/f83106f562b9c7a81a34137590fa34e3f356ab0d/src/components/Errors/ErrorDetails/ErrorDetailsCardContent/index.tsx#L36

**Comment by kshmidt-digma** [comment]
According to the Posthog event logs error occurred due to `HTTP 503 Service Temporarily Unavailable` response from the backend to the plugin (a lot of connection errors in parallel with that)
