### ISSUE TITLE
 Cannot read properties of undefined (reading 'key') at onGoToNextStep

### ISSUE THREAD

**Issue by kshmidt-digma** [digma-ai/digma-ui#936]
TypeError: Cannot read properties of undefined (reading 'key') at onGoToNextStep (https://installationwizard/index.js:338:3155) at https://installationwizard/index.js:146:2853 at al (https://installationwizard/index.js:2:1206094) at Tc (https://installationwizard/index.js:2:1226216) at https://installationwizard/index.js:2:1222820 at v (https://installationwizard/index.js:2:2043140) at MessagePort.w (https://installationwizard/index.js:2:2043672)

**Comment by doppleware** [comment]
@kshmidt-digma close or handle?

**Comment by kshmidt-digma** [comment]
we need to find the scenario and handle it properly
